### ISSUE TITLE
Cannot start conferences anymore if  LDAP Auth is active with latest stable 5765

### ISSUE THREAD

**Issue by Twilek-de** [jitsi/docker-jitsi-meet#1018]
Everything seems to work, but then the login window gets stuck on "Getting session ID" (or something similar, as I see the german translation). In the logs it says that LDAP Auth was successfull. When I turn off Auth alltogether things work fine again. Same setup worked with the stable version before that.

**Comment by Twilek-de** [comment]
Tried JWT Auth. Shows a successfull login in the logs und then a login prompt on the page. I think authorisation is seriously broken in this release....

**Comment by tob123** [comment]
i have the same issue using internal authentication.
for me it is fixed by adjusting /config/jicofo.conf by adding 'client-proxy = "focus.meet.jitsi"' to the xmpp client configuration.
this is also referenced here for the debian package: https://github.com/jitsi/jitsi-meet/pull/8439/files

**Comment by saghul** [comment]
Care to make a PR?

**Comment by aminvakil** [comment]
Same problem here using jwt auth and rocketchat 3.11.3

**Comment by aminvakil** [comment]
Adding `client-proxy = "focus.meet.jitsi"` in
https://github.com/jitsi/docker-jitsi-meet/blob/8d2a29f2864cbff5faeeb73ae8e06fbb3bed08b8/jicofo/rootfs/defaults/jicofo.conf#L132-L140
did not fix the problem for me neither.

**Comment by TheSleepySlee** [comment]
> i have the same issue using internal authentication.
> for me it is fixed by adjusting /config/jicofo.conf by adding 'client-proxy = "focus.meet.jitsi"' to the xmpp client configuration.
> this is also referenced here for the debian package: https://github.com/jitsi/jitsi-meet/pull/8439/files

hi, can you details how you are fixing the issue?
I tried to edit .jitsi-meet-cfg/jicofo/jicofo.conf but it seems it gets replaced when I start the container again
Editing docker-jitsi-meet/jicofo/rootfs/defaults/jicofo.conf and doing docker-compose up don't work either

thanks

**Comment by daradib** [comment]
Editing `.jitsi-meet-cfg/jicofo/jicofo.conf` as described fixed internal auth for me in stable-5765. Thanks!

@aminvakil  @TheSleepySlee try restarting jicofo without restarting the container to avoid regenerating the file:

    docker-compose exec jicofo s6-svc -r /var/run/s6/services/jicofo

If you instead edited `docker-jitsi-meet/jicofo/rootfs/defaults/jicofo.conf`, did you also rebuild the jicofo image and reference that image in `docker-compose.yml`?

**Comment by tob123** [comment]
@daradib I use a bit of a different image. it does not copy jicofo.conf but just directly starts. I will try a PR for the image offered by Jitsi.

**Comment by Javinator9889** [comment]
This issue happens to my installation also after upgrading from previous version
Will try the proposed fix and let you know if it works (running a reverse proxy installation behind NGINX)

**Comment by Javinator9889** [comment]
> This issue happens to my installation also after upgrading from previous version
> Will try the proposed fix and let you know if it works (running a reverse proxy installation behind NGINX)

I confirm the **proposed solution works** but *every time you restart the containers the newly added config dissapears*.

Here is a hotfix that should work in \*all\* distributions:
```shell
# cd into the Docker Jitsi directory
cd docker-jitsi-meet

# Stop de containers
sudo docker-compose down

# Update the configuration
sed -i -E '/^\s+disable-certificate-verification = true/a \\tclient-proxy = "focus.meet.jitsi"' jicofo/rootfs/defaults/jicofo.conf

# Replace tag - by default, it is "stable-5765" but we want to use "latest", which is the one
# built by Makefile
sed -i 's/:stable-5765/:latest/' docker-compose.yml

# Rebuild the containers -- THIS STEP IS MANDATORY
sudo make all

# Finally, start again the containers
sudo docker-compose up -d
```

You can check this is working properly by looking for `client-config` at your config directory:
```shell
source .env
cat ${CONFIG}/jicofo/jicofo.conf | grep client-proxy
```

Hope this helps everyone :)

**Comment by Twilek-de** [comment]
Thanks! Looking forward to the bufixed release.

**Comment by mammo0** [comment]
Hello,

Thanks @Javinator9889 
I modified your steps to have a workaround where you don't have to rebuild the docker images:

```shell
# cd into the Docker Jitsi directory
cd docker-jitsi-meet

# attach to the running jifoco container
docker-compose exec jifoco bash

    # update the default configuration inside the container
    sed -i -E '/^\s+disable-certificate-verification = true/a \\tclient-proxy = "focus.meet.jitsi"' /defaults/jicofo.conf

    # exit from the container
    exit

# restart Jitsi
docker-compose restart
```

**Please note:** This method only survives restarts of the containers. If you remove the containers (e.g. with `docker-compose down`), you have to do the steps from above again after the containers are created.

**Comment by TheSleepySlee** [comment]
> ```shell
> docker-compose exec jifoco bash
> ```

@mammo0 excellent, works like a charm, except this typo: jifoco instead of jicofo 🤣

**Comment by mammo0** [comment]
> @mammo0 excellent, works like a charm, except this typo: jifoco instead of jicofo

oops :sweat_smile:
now it should work

**Comment by blu2lz** [comment]
Thanks @Javinator9889, @mammo and of course @tob123 who posted the solution.
I want to add an even shorter version without restarting everything, only the relevant jicofo container:

```
sudo docker-compose exec jicofo sed -i -E '/^\s+disable-certificate-verification = true/a \\tclient-proxy = "focus.meet.jitsi"' /defaults/jicofo.conf
sudo docker-compose restart jicofo
```

**Comment by saghul** [comment]
stable-5765-1 is out. Sorry everyone for the trouble and thanks @tob123 for the quick patch.
