### ISSUE TITLE
Screen share goes blank if a 3rd participant joins

### ISSUE THREAD

**Issue by vskrish11** [jitsi/docker-jitsi-meet#1376]
### Description:

Similar to issue jitsi/jitsi-meet#3878 reported in 2019, we are facing an issue where Screen share does not work if there are 3 or more participants. It works between two participants but when a 3rd one joins, screen share goes black. We took the latest version of Jitsi Meet from GitHub just an hour ago and installed. Video is working fine.
git clone https://github.com/jitsi/docker-jitsi-meet

We see below entry in config.js
...
config.testing.capScreenshareBitrate = 1;
config.testing.octo.probability = 0;
...
But did not find an entry for "capScreenshareBitrate"

We also tried the workaround stated for issue jitsi/jitsi-meet#3878 (turning video on and then sharing screen). But that did not work either.

Our OS is CenOS 7. Faced same behaviour on both Chrome and Edge.

Please check and let us know how to fix this. Appreciate your help.

**Comment by saghul** [comment]
The latest stable I just pushed should have this fixed. Please drop a comment otherwise.

**Comment by vskrish11** [comment]
> The latest stable I just pushed should have this fixed. Please drop a comment otherwise.

Sure, will check. As of now I see this as the latest stable release - 2.0.7648 but it was published 7 days ago. What is the release version that you pushed now ?

**Comment by damencho** [comment]
https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-7648-2

**Comment by this-user** [comment]
We were still experiencing some issues with screen sharing from a Firefox client even with MS enabled manually, but it seems that it does work now with the latest build.

**Comment by vskrish11** [comment]
> https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-7648-2

Sorry but am facing the same issue even with this release. Works when sharing is done through Firefox. Screen share crashes when Screen share was being done through Chrome and 3rd participant joins. Below is the browser console log from Chrome where it was being shared, in case it helps.

Logger.js:154 2022-08-19T02:37:49.100Z [modules/xmpp/ChatRoom.js] <Sr.onPresence>:  entered newtest@muc.meet.jitsi/916f2d47 {isReplaceParticipant: 0, affiliation: 'none', role: 'participant', jid: 'o5namhocbj8d1bgamokfwdsj@meet.jitsi/nAKi5ipXXlk4', isFocus: false, …}
index.js:154 2022-08-19T02:37:49.192Z [conference.js] <r.<anonymous>>:  USER 916f2d47 connected: kn {_jid: 'newtest@muc.meet.jitsi/916f2d47', _id: '916f2d47', _conference: Mh, _displayName: 'KrishnanMobileWeb', _supportsDTMF: false, …}
Logger.js:154 2022-08-19T02:37:49.196Z [JitsiConference.js] <Mh._maybeStartOrStopP2P>:  Will stop P2P with: newtest@muc.meet.jitsi/4d760e6d
Logger.js:154 2022-08-19T02:37:49.197Z [JitsiConference.js] <Mh._resumeMediaTransferForJvbConnection>:  Resuming media transfer over the JVB connection...
Logger.js:154 2022-08-19T02:37:49.200Z [modules/xmpp/JingleSessionPC.js] <jo.setMediaTransferActive>:  JingleSessionPC[session=JVB,initiator=false,sid=1aqkkqsf5ftlb] Queued make video active, audio active task
Logger.js:154 2022-08-19T02:37:49.204Z [JitsiConference.js] <Mh._stopP2PSession>:  Stopping remote stats for P2P connection
Logger.js:154 2022-08-19T02:37:49.207Z [JitsiConference.js] <Mh._stopP2PSession>:  Stopping CallStats for P2P connection
Logger.js:154 2022-08-19T02:37:49.217Z [modules/xmpp/JingleSessionPC.js] <jo.terminate>:  JingleSessionPC[session=P2P,initiator=false,sid=583abb2ebcf6] Sending session-terminate
Logger.js:154 2022-08-19T02:37:49.222Z [modules/xmpp/JingleSessionPC.js] <jo.onTerminated>:  JingleSessionPC[session=P2P,initiator=false,sid=583abb2ebcf6] Session terminated undefined undefined
Logger.js:154 2022-08-19T02:37:49.237Z [JitsiConference.js] <Mh._setP2PStatus>:  Peer to peer connection closed!
Logger.js:154 2022-08-19T02:37:49.272Z [modules/xmpp/JingleSessionPC.js] <jo.setSenderVideoConstraint>:  JingleSessionPC[session=JVB,initiator=false,sid=1aqkkqsf5ftlb] setSenderVideoConstraint: 180, sourceName: afa34960-v0
Logger.js:154 2022-08-19T02:37:49.279Z [modules/xmpp/JingleSessionPC.js] <jo.setSenderVideoConstraint>:  JingleSessionPC[session=JVB,initiator=false,sid=1aqkkqsf5ftlb] setSenderVideoConstraint: 2160, sourceName: afa34960-v1
Logger.js:154 2022-08-19T02:37:49.386Z [modules/RTC/TPCUtils.js] <Od.setMediaTransferActive>:  TPC[id=2,type=JVB] Enabling audio media transfer.
Logger.js:154 2022-08-19T02:37:49.388Z [modules/RTC/TPCUtils.js] <Od.setMediaTransferActive>:  TPC[id=2,type=JVB] Enabling video media transfer.
Logger.js:154 2022-08-19T02:37:49.400Z [modules/RTC/TraceablePeerConnection.js] <Ld.close>:  TPC[id=1,type=P2P] Closing peerconnection
Logger.js:154 2022-08-19T02:37:49.433Z [JitsiConference.js] Resumed media transfer over the JVB connection!
Logger.js:154 2022-08-19T02:37:49.555Z [modules/xmpp/JingleSessionPC.js] <peerconnection.onnegotiationneeded>:  JingleSessionPC[session=JVB,initiator=false,sid=1aqkkqsf5ftlb] onnegotiationneeded fired on TPC[id=2,type=JVB]
Logger.js:154 2022-08-19T02:37:49.619Z [modules/RTC/TraceablePeerConnection.js] <Ld._remoteTrackAdded>:  TPC[id=2,type=JVB] ignored remote 'stream added' event for non-user stream[id=mixedmslabel]
Logger.js:154 2022-08-19T02:37:49.620Z [modules/RTC/TraceablePeerConnection.js] <Ld._remoteTrackAdded>:  TPC[id=2,type=JVB] ignored remote 'stream added' event for non-user stream[id=mixedmslabel]
Logger.js:154 2022-08-19T02:37:49.664Z [modules/RTC/TraceablePeerConnection.js] <Ld.setSenderVideoConstraints>:  TPC[id=2,type=JVB] Setting degradation preference [preference=maintain-resolution,track=LocalTrack[4,video]
Logger.js:154 2022-08-19T02:37:49.669Z [modules/RTC/TraceablePeerConnection.js] <Ld.setSenderVideoConstraints>:  TPC[id=2,type=JVB] setting max height=2160,encodings=[{"active":false,"adaptivePtime":false,"networkPriority":"low","priority":"low","maxBitrate":500000},{"active":false,"adaptivePtime":false,"networkPriority":"low","priority":"low","maxBitrate":500000},{"active":true,"adaptivePtime":false,"networkPriority":"low","priority":"low","maxBitrate":500000}]
Logger.js:154 2022-08-19T02:37:49.683Z [modules/xmpp/JingleSessionPC.js] <jo.notifyMySSRCUpdate>:  JingleSessionPC[session=JVB,initiator=false,sid=1aqkkqsf5ftlb] Sending source-add for video ssrcs=145413458,699696506,803052066,995373620,1400704633,1459196610,2592491545,2908040574,3064513269,3113707187,3465909062,3597568925
Logger.js:154 2022-08-19T02:37:51.361Z [modules/xmpp/strophe.jingle.js] <Bo.onJingle>:  invalid session id: 583abb2ebcf6
r @ Logger.js:154
onJingle @ strophe.jingle.js:115
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5290
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:5257
setTimeout (async)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
sendIQ @ strophe.umd.js:2740
sendIQ @ XmppConnection.js:511
notifyMySSRCUpdate @ JingleSessionPC.js:2744
(anonymous) @ JingleSessionPC.js:655
Promise.then (async)
e @ JingleSessionPC.js:652
_processQueueTasks @ AsyncQueue.js:30
(anonymous) @ async.mjs:4005
process @ async.mjs:1668
(anonymous) @ async.mjs:1526
(anonymous) @ async.mjs:68
BridgeChannel.js:84 WebSocket connection to 'wss://sarkmobilesolutions.com/colibri-ws/172.18.0.4/8bafdeac6d0ae571/afa34960?pwd=6h5sq8l0b6d8c43s93jm8djf0g' failed: 
_initWebSocket @ BridgeChannel.js:84
t @ BridgeChannel.js:103
Logger.js:154 2022-08-19T02:37:51.486Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-08-19T02:37:51.487Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
e.onclose @ BridgeChannel.js:433
Logger.js:154 2022-08-19T02:37:51.759Z [modules/xmpp/strophe.jingle.js] <Bo.onJingle>:  invalid session id: 583abb2ebcf6
r @ Logger.js:154
onJingle @ strophe.jingle.js:115
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5290
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:5257
setTimeout (async)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
send @ XmppConnection.js:491
onJingle @ strophe.jingle.js:117
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onRequestStateChange @ strophe.umd.js:5012
XMLHttpRequest.send (async)
d @ strophe.umd.js:5123
_processRequest @ strophe.umd.js:5137
_throttledRequestHandler @ strophe.umd.js:5290
_onIdle @ strophe.umd.js:4901
_onIdle @ strophe.umd.js:3881
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:3886
setTimeout (async)
_onIdle @ strophe.umd.js:3885
(anonymous) @ strophe.umd.js:5257
setTimeout (async)
_send @ strophe.umd.js:5256
send @ strophe.umd.js:2583
sendIQ @ strophe.umd.js:2740
sendIQ @ XmppConnection.js:511
notifyMySSRCUpdate @ JingleSessionPC.js:2744
(anonymous) @ JingleSessionPC.js:655
Promise.then (async)
e @ JingleSessionPC.js:652
_processQueueTasks @ AsyncQueue.js:30
(anonymous) @ async.mjs:4005
process @ async.mjs:1668
(anonymous) @ async.mjs:1526
(anonymous) @ async.mjs:68

**Comment by damencho** [comment]
> Logger.js:154 2022-08-19T02:37:51.486Z [modules/RTC/BridgeChannel.js] <e.onclose>: Channel closed by server
> Logger.js:154 2022-08-19T02:37:51.487Z [modules/RTC/BridgeChannel.js] <e.onclose>: Channel closed: 1006

You can check the nginx logs, why the websocket was closed.

**Comment by vskrish11** [comment]
> > Logger.js:154 2022-08-19T02:37:51.486Z [modules/RTC/BridgeChannel.js] <e.onclose>: Channel closed by server
> > Logger.js:154 2022-08-19T02:37:51.487Z [modules/RTC/BridgeChannel.js] <e.onclose>: Channel closed: 1006
> 
> You can check the nginx logs, why the websocket was closed.

But if it was closed, shouldn't it have affected Screen share between even two participants ? Why does this happen only when a 3rd participant joins ?

**Comment by damencho** [comment]
Cause you go to the bridge and there are certain messages expected to be sent.

**Comment by vskrish11** [comment]
> 
This is the pattern to screenshare issue we face with release, 7648-3.
Observation 1 - Video sharing works with 3 or more participants
Observation 2 - If a participant turns on video, any participant can do screenshare even with 3 or more participants
Observation 3 - If a participant turns on video and then turns it off, any participant can do screenshare even with 3 or more participants
Observation 4 - If a participant attempts screenshare before anyone has turned video on, screenshare breaks when 3rd participant joins. NOTE: this issue is only when using Chrome or Edge, screenshare works fine with Firefox

This is the console logs from Chrome browser on Observation 4 (when screenshare crashed on 3rd person joining). Please check and let us know how to get this addressed.

A4L-24-Aug-2022:62 (TIME) index.html loaded:	 686.1000000238419
Logger.js:154 2022-08-26T12:05:28.214Z [modules/browser/BrowserCapabilities.js] <new <anonymous>>:  This appears to be chrome, ver: 104.0.0.0
Logger.js:154 2022-08-26T12:05:28.299Z [modules/statistics/LocalStatsCollector.js] <tn.connectAudioContext>:  Connecting audio context
? The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
tn.connectAudioContext @ lib-jitsi-meet.min.js:2
Logger.js:154 2022-08-26T12:05:30.156Z [modules/RTC/RTCUtils.js] <Lc>:  list of media devices has changed: Array(7)
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:05:30.485Z [features/base/redux] <Object.persistState>:  redux state persisted. 02d8ca038e6cee055c93087fd4da552f -> 2e83d450fc33736cd4a08783589de4ef
Logger.js:154 2022-08-26T12:05:30.639Z [FeatureFlags] <Object.init>:  Source name signaling: true, Send multiple video streams: true, SSRC rewriting supported: false, uses Unified plan: true
Logger.js:154 2022-08-26T12:05:30.640Z [modules/RTC/RTCUtils.js] <Wn.init>:  Disable AP: false
Logger.js:154 2022-08-26T12:05:30.641Z [modules/RTC/RTCUtils.js] <Wn.init>:  Stereo: false
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:05:30.647Z [features/base/media] Start muted: 
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:05:30.655Z [features/base/media] Start audio only set to false
Logger.js:154 2022-08-26T12:05:30.656Z [modules/statistics/AnalyticsAdapter.js] <Object.dispose>:  Disposing of analytics adapter.
r @ Logger.js:154
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:05:30.656Z [features/analytics] Initialized 0 analytics handlers
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:05:30.850Z [index.web] <HTMLDocument.<anonymous>>:  (TIME) document ready:	 4205.799999952316
A4L-24-Aug-2022:48 DOMException: Failed to register a ServiceWorker for scope ('https://jitsi.<domain>.com:8445/') with script ('https://jitsi.<domain>.com:8445/pwa-worker.js'): An SSL certificate error occurred when fetching the script.
Logger.js:154 2022-08-26T12:05:30.962Z [modules/RTC/RTCUtils.js] Audio output device set to default
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:05:31.083Z [features/base/connection] Using service URL https://jitsi.<domain>.com:8445/http-bind
Logger.js:154 2022-08-26T12:05:31.087Z [modules/xmpp/xmpp.js] <sa._initStrophePlugins>:  P2P STUN servers:  Array(1)
Logger.js:154 2022-08-26T12:05:31.101Z [modules/xmpp/xmpp.js] <sa.initFeaturesList>:  Source-name signaling is enabled
Logger.js:154 2022-08-26T12:05:31.102Z [modules/xmpp/xmpp.js] <sa.initFeaturesList>:  Receiving multiple video streams is enabled
Logger.js:154 2022-08-26T12:05:31.105Z [modules/xmpp/xmpp.js] <sa.connectionHandler>:  (TIME) Strophe connecting:	 4459.5
Logger.js:154 2022-08-26T12:05:31.120Z [modules/RTC/RTCUtils.js] <Wn.<anonymous>>:  Got media constraints:  {"video":{"height":{"ideal":720},"width":{"ideal":1280},"facingMode":"user"},"audio":{"autoGainControl":true,"echoCancellation":true,"noiseSuppression":true}}
Logger.js:154 2022-08-26T12:05:32.589Z [modules/RTC/RTCUtils.js] onUserMediaSuccess
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:05:32.610Z [features/base/redux] <Object.persistState>:  redux state persisted. 2e83d450fc33736cd4a08783589de4ef -> 6076b189a16554260b91df7b00932dfd
Logger.js:154 2022-08-26T12:05:34.961Z [modules/xmpp/XmppConnection.js] <js._maybeEnableStreamResume>:  Stream resume enabled, but WebSockets are not enabled
r @ Logger.js:154
Logger.js:154 2022-08-26T12:05:34.962Z [modules/xmpp/strophe.ping.js] <Vs.startInterval>:  XMPP pings will be sent every 10000 ms
Logger.js:154 2022-08-26T12:05:34.964Z [modules/xmpp/xmpp.js] <sa.connectionHandler>:  (TIME) Strophe connected:	 8318.700000047684
Logger.js:154 2022-08-26T12:05:34.965Z [modules/xmpp/xmpp.js] <sa.connectionHandler>:  My Jabber ID: 0sp-on16asaewnkjim6pm_ci@meet.jitsi/1M5JOwXWmE2D
Logger.js:154 2022-08-26T12:05:35.976Z [modules/xmpp/strophe.jingle.js] getting turn credentials with extdisco:2 failed, trying extdisco:1
r @ Logger.js:154
Logger.js:154 2022-08-26T12:05:36.962Z [modules/xmpp/strophe.jingle.js] getting turn credentials failed
r @ Logger.js:154
Logger.js:154 2022-08-26T12:05:36.964Z [modules/xmpp/strophe.jingle.js] is mod_turncredentials or similar installed and configured?
r @ Logger.js:154
Logger.js:154 2022-08-26T12:05:55.877Z [modules/RTC/JitsiLocalTrack.js] Mute LocalTrack[2,video]: true
Logger.js:154 2022-08-26T12:05:56.320Z [modules/RTC/JitsiLocalTrack.js] Mute LocalTrack[1,audio]: true
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:05:56.789Z [features/base/redux] <Object.persistState>:  redux state persisted. 6076b189a16554260b91df7b00932dfd -> 5399c9d8783eba676eb673c07bace8bc
Logger.js:154 2022-08-26T12:06:42.437Z [modules/xmpp/xmpp.js] <sa.createRoom>:  JID 0sp-on16asaewnkjim6pm_ci@meet.jitsi/1M5JOwXWmE2D using MUC nickname 000ad336
Logger.js:154 2022-08-26T12:06:42.438Z [modules/xmpp/ChatRoom.js] <new Sr>:  Joined MUC as a4l-24-aug-2022@muc.meet.jitsi/000ad336
Logger.js:154 2022-08-26T12:06:42.442Z [modules/statistics/AvgRTPStatsReporter.js] <new Vl>:  Avg RTP stats will be calculated every 15 samples
Logger.js:154 2022-08-26T12:06:42.444Z [JitsiConference.js] <new Mh>:  backToP2PDelay: 5
Logger.js:154 2022-08-26T12:06:42.444Z [JitsiConference.js] <new Mh>:  End-to-End Encryption is supported
Logger.js:154 2022-08-26T12:06:42.482Z [modules/xmpp/moderator.js] <pr.setFocusUserJid>:  Focus jid set to:  focus@auth.meet.jitsi
Logger.js:154 2022-08-26T12:06:42.483Z [modules/xmpp/moderator.js] <pr.createConferenceIq>:  Session ID: null machine UID: c204562f95e284b848470e3f76f2cd56
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:06:42.490Z [conference.js] Initialized with 0 local tracks
Logger.js:154 2022-08-26T12:06:42.561Z [modules/xmpp/moderator.js] <pr.parseConfigOptions>:  Authentication enabled: false
Logger.js:154 2022-08-26T12:06:42.562Z [modules/xmpp/moderator.js] <pr.parseConfigOptions>:  External authentication enabled: false
Logger.js:154 2022-08-26T12:06:42.575Z [modules/xmpp/moderator.js] <pr.parseConfigOptions>:  Sip gateway enabled:  false
Logger.js:154 2022-08-26T12:06:42.688Z [modules/xmpp/ChatRoom.js] <Sr.onPresence>:  (TIME) MUC join started:	 76037.29999995232
Logger.js:154 2022-08-26T12:06:42.763Z [modules/xmpp/ChatRoom.js] <Sr.onPresence>:  entered a4l-24-aug-2022@muc.meet.jitsi/a12abe1b Object
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:06:42.840Z [conference.js] <r.<anonymous>>:  USER a12abe1b connected: kn
Logger.js:154 2022-08-26T12:06:42.846Z [modules/xmpp/ChatRoom.js] <Sr.onPresence>:  entered a4l-24-aug-2022@muc.meet.jitsi/focus Object
Logger.js:154 2022-08-26T12:06:42.854Z [modules/version/ComponentsVersions.js] Got focus version: 1.0.911
Logger.js:154 2022-08-26T12:06:42.864Z [JitsiConference.js] <Mh._updateProperties>:  Audio unmute permissions set by Jicofo to false
Logger.js:154 2022-08-26T12:06:42.877Z [JitsiConference.js] <Mh._updateProperties>:  Video unmute permissions set by Jicofo to false
Logger.js:154 2022-08-26T12:06:42.881Z [modules/xmpp/ChatRoom.js] <Sr.onPresence>:  Jicofo supports restart by terminate: true
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:06:42.887Z [conference.js] <r.<anonymous>>:  My role changed, new role: none
Logger.js:154 2022-08-26T12:06:42.921Z [modules/xmpp/ChatRoom.js] <Sr.onPresence>:  (TIME) MUC joined:	 76275.20000004768
Logger.js:154 2022-08-26T12:06:43.024Z [JitsiConference.js] <Mh._maybeStartOrStopP2P>:  Will start P2P with: a4l-24-aug-2022@muc.meet.jitsi/a12abe1b
Logger.js:154 2022-08-26T12:06:43.026Z [JitsiConference.js] <Mh._startP2PSession>:  Created new P2P JingleSession a4l-24-aug-2022@muc.meet.jitsi/000ad336 a4l-24-aug-2022@muc.meet.jitsi/a12abe1b
Logger.js:154 2022-08-26T12:06:43.035Z [modules/RTC/TraceablePeerConnection.js] <new Ld>:  Using RTCRtpTransceiver#setCodecPreferences for codec selection
Logger.js:154 2022-08-26T12:06:43.036Z [modules/RTC/TraceablePeerConnection.js] <new Ld>:  Create new TPC[id=1,type=P2P]
Logger.js:154 2022-08-26T12:06:43.036Z [JitsiConference.js] <Mh._startP2PSession>:  Starting CallStats for P2P connection...
Logger.js:154 2022-08-26T12:06:43.053Z [modules/xmpp/ChatRoom.js] <Sr.onMessage>:  Subject is changed to 
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:06:43.156Z [modules/UI/videolayout/LargeVideoManager.js] hover in a12abe1b
Logger.js:154 2022-08-26T12:06:43.395Z [modules/xmpp/JingleSessionPC.js] <jo.sendIceCandidate>:  JingleSessionPC[session=P2P,initiator=true,sid=a2b613c5cfc6] sendIceCandidate: last candidate
Logger.js:154 2022-08-26T12:06:43.429Z [modules/xmpp/JingleSessionPC.js] <jo.sendIceCandidates>:  JingleSessionPC[session=P2P,initiator=true,sid=a2b613c5cfc6] sendIceCandidates [{"candidate":"candidate:899937325 1 udp 2122260223 192.168.0.8 63479 typ host generation 0 ufrag NT2z network-id 1 network-cost 10","sdpMid":"0","sdpMLineIndex":0},{"candidate":"candidate:2633792504 1 udp 1686052607 116.75.115.172 63479 typ srflx raddr 192.168.0.8 rport 63479 generation 0 ufrag NT2z network-id 1 network-cost 10","sdpMid":"0","sdpMLineIndex":0},{"candidate":"candidate:2065696989 1 tcp 1518280447 192.168.0.8 9 typ host tcptype active generation 0 ufrag NT2z network-id 1 network-cost 10","sdpMid":"0","sdpMLineIndex":0}]
Logger.js:154 2022-08-26T12:06:43.927Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=P2P,initiator=true,sid=a2b613c5cfc6] Got RESULT for "session-initiate"
Logger.js:154 2022-08-26T12:06:44.032Z [JitsiConference.js] <Mh.onCallAccepted>:  P2P setAnswer
Logger.js:154 2022-08-26T12:06:44.035Z [modules/xmpp/JingleSessionPC.js] <jo.setReceiverVideoConstraint>:  JingleSessionPC[session=P2P,initiator=true,sid=a2b613c5cfc6] setReceiverVideoConstraint - max frame height: 2160 sourceReceiverConstraints: [object Map]
Logger.js:154 2022-08-26T12:06:44.064Z [modules/RTC/TraceablePeerConnection.js] <Ld._remoteTrackAdded>:  TPC[id=1,type=P2P] adding remote track for stream[id=a12abe1b-audio-0-1,type=audio]
Logger.js:154 2022-08-26T12:06:44.064Z [modules/RTC/TraceablePeerConnection.js] <Ld._remoteTrackAdded>:  TPC[id=1,type=P2P] creating remote track[endpoint=a12abe1b,ssrc=4045768040,type=audio,sourceName=a12abe1b-a0]
Logger.js:154 2022-08-26T12:06:44.067Z [JitsiConference.js] <Mh.onRemoteTrackAdded>:  Trying to add remote P2P track, when not in P2P - IGNORED
Logger.js:154 2022-08-26T12:06:44.236Z [JitsiConference.js] <Mh.onTransportInfo>:  P2P addIceCandidates
Logger.js:154 2022-08-26T12:06:44.242Z [modules/xmpp/JingleSessionPC.js] <peerconnection.oniceconnectionstatechange>:  (TIME) ICE checking P2P:	 77596.89999997616
Logger.js:154 2022-08-26T12:06:44.412Z [modules/RTC/TPCUtils.js] <Od.setMediaTransferActive>:  TPC[id=1,type=P2P] Enabling video media transfer.
Logger.js:154 2022-08-26T12:06:45.162Z [modules/xmpp/strophe.jingle.js] <Bo.onJingle>:  Found a JSON-encoded element in session-initiate, translating to standard Jingle.
Logger.js:154 2022-08-26T12:06:45.164Z [modules/xmpp/strophe.jingle.js] <Bo.onJingle>:  (TIME) received session-initiate:	 78517.29999995232
Logger.js:154 2022-08-26T12:06:45.169Z [modules/RTC/TraceablePeerConnection.js] <new Ld>:  Using RTCRtpTransceiver#setCodecPreferences for codec selection
Logger.js:154 2022-08-26T12:06:45.170Z [modules/RTC/TraceablePeerConnection.js] <new Ld>:  Create new TPC[id=2,type=JVB]
Logger.js:154 2022-08-26T12:06:45.175Z [JitsiConference.js] <Mh._acceptJvbIncomingCall>:  Starting CallStats for JVB connection...
Logger.js:154 2022-08-26T12:06:45.176Z [modules/statistics/RTPStatsCollector.js] <_n.start>:  Using RTCRtpSynchronizationSource for remote audio levels
2Logger.js:154 2022-08-26T12:06:45.204Z [modules/RTC/TraceablePeerConnection.js] <Ld._remoteTrackAdded>:  TPC[id=2,type=JVB] ignored remote 'stream added' event for non-user stream[id=mixedmslabel]
Logger.js:154 2022-08-26T12:06:45.223Z [modules/xmpp/JingleSessionPC.js] <jo.sendSessionAccept>:  JingleSessionPC[session=JVB,initiator=false,sid=2cu3e6i10ousr] Sending session-accept
Logger.js:154 2022-08-26T12:06:45.227Z [modules/xmpp/JingleSessionPC.js] <peerconnection.oniceconnectionstatechange>:  (TIME) ICE checking JVB:	 78581.79999995232
BridgeChannel.js:84 WebSocket connection to 'wss://jitsi.<domain>.com/colibri-ws/172.25.0.5/c28e8ff0e64740b3/000ad336?pwd=7sitbn7trtsl2rn1qddr8t15m2' failed: 
_initWebSocket @ BridgeChannel.js:84
Logger.js:154 2022-08-26T12:06:45.290Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-08-26T12:06:45.290Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
Logger.js:154 2022-08-26T12:06:45.346Z [modules/xmpp/JingleSessionPC.js] <jo.sendIceCandidate>:  JingleSessionPC[session=JVB,initiator=false,sid=2cu3e6i10ousr] sendIceCandidate: last candidate
Logger.js:154 2022-08-26T12:06:45.365Z [modules/xmpp/JingleSessionPC.js] <peerconnection.oniceconnectionstatechange>:  (TIME) ICE connected JVB:	 78720.70000004768
Logger.js:154 2022-08-26T12:06:45.389Z [modules/xmpp/JingleSessionPC.js] <jo.sendIceCandidates>:  JingleSessionPC[session=JVB,initiator=false,sid=2cu3e6i10ousr] sendIceCandidates [{"candidate":"candidate:899937325 1 udp 2122260223 192.168.0.8 53134 typ host generation 0 ufrag D7Jl network-id 1 network-cost 10","sdpMid":"0","sdpMLineIndex":0},{"candidate":"candidate:2065696989 1 tcp 1518280447 192.168.0.8 9 typ host tcptype active generation 0 ufrag D7Jl network-id 1 network-cost 10","sdpMid":"0","sdpMLineIndex":0}]
Logger.js:154 2022-08-26T12:06:45.559Z [modules/xmpp/strophe.jingle.js] <Bo.onJingle>:  Found a JSON-encoded element in source-add, translating to standard Jingle.
Logger.js:154 2022-08-26T12:06:45.570Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=JVB,initiator=false,sid=2cu3e6i10ousr] Processing addRemoteStream
Logger.js:154 2022-08-26T12:06:45.597Z [modules/RTC/TraceablePeerConnection.js] <Ld._remoteTrackAdded>:  TPC[id=2,type=JVB] adding remote track for stream[id=a12abe1b-audio-0-2,type=audio]
Logger.js:154 2022-08-26T12:06:45.598Z [modules/RTC/TraceablePeerConnection.js] <Ld._remoteTrackAdded>:  TPC[id=2,type=JVB] creating remote track[endpoint=a12abe1b,ssrc=3353448976,type=audio,sourceName=a12abe1b-a0]
JitsiRemoteTrack.js:294 (TIME) Render audio:	 79101.89999997616
JitsiRemoteTrack.js:313 (TIME) TTFM audio:	 75383.60000002384
Logger.js:154 2022-08-26T12:06:45.769Z [modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=JVB,initiator=false,sid=2cu3e6i10ousr] addRemoteStream - OK
BridgeChannel.js:84 WebSocket connection to 'wss://jitsi.<domain>.com/colibri-ws/172.25.0.5/c28e8ff0e64740b3/000ad336?pwd=7sitbn7trtsl2rn1qddr8t15m2' failed: 
_initWebSocket @ BridgeChannel.js:84
Logger.js:154 2022-08-26T12:06:46.391Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-08-26T12:06:46.392Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
BridgeChannel.js:84 WebSocket connection to 'wss://jitsi.<domain>.com/colibri-ws/172.25.0.5/c28e8ff0e64740b3/000ad336?pwd=7sitbn7trtsl2rn1qddr8t15m2' failed: 
_initWebSocket @ BridgeChannel.js:84
Logger.js:154 2022-08-26T12:06:48.408Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-08-26T12:06:48.408Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
BridgeChannel.js:84 WebSocket connection to 'wss://jitsi.<domain>.com/colibri-ws/172.25.0.5/c28e8ff0e64740b3/000ad336?pwd=7sitbn7trtsl2rn1qddr8t15m2' failed: 
_initWebSocket @ BridgeChannel.js:84
Logger.js:154 2022-08-26T12:06:52.436Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-08-26T12:06:52.436Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
Logger.js:154 2022-08-26T12:06:59.343Z [modules/xmpp/strophe.jingle.js] <Bo.onJingle>:  terminating... a2b613c5cfc6
Logger.js:154 2022-08-26T12:06:59.379Z [modules/xmpp/JingleSessionPC.js] <jo.onTerminated>:  JingleSessionPC[session=P2P,initiator=true,sid=a2b613c5cfc6] Session terminated connectivity-error ICE FAILED
Logger.js:154 2022-08-26T12:06:59.381Z [JitsiConference.js] <Mh.onCallEnded>:  Call ended: connectivity-error - ICE FAILED P2P ?true
Logger.js:154 2022-08-26T12:06:59.382Z [JitsiConference.js] <Mh._stopP2PSession>:  Stopping remote stats for P2P connection
Logger.js:154 2022-08-26T12:06:59.382Z [JitsiConference.js] <Mh._stopP2PSession>:  Stopping CallStats for P2P connection
Logger.js:154 2022-08-26T12:06:59.384Z [modules/RTC/TraceablePeerConnection.js] <Ld.close>:  TPC[id=1,type=P2P] Closing peerconnection
BridgeChannel.js:84 WebSocket connection to 'wss://jitsi.<domain>.com/colibri-ws/172.25.0.5/c28e8ff0e64740b3/000ad336?pwd=7sitbn7trtsl2rn1qddr8t15m2' failed: 
_initWebSocket @ BridgeChannel.js:84
Logger.js:154 2022-08-26T12:07:00.436Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-08-26T12:07:00.436Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
BridgeChannel.js:84 WebSocket connection to 'wss://jitsi.<domain>.com/colibri-ws/172.25.0.5/c28e8ff0e64740b3/000ad336?pwd=7sitbn7trtsl2rn1qddr8t15m2' failed: 
_initWebSocket @ BridgeChannel.js:84
Logger.js:154 2022-08-26T12:07:16.442Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-08-26T12:07:16.443Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
BridgeChannel.js:84 WebSocket connection to 'wss://jitsi.<domain>.com/colibri-ws/172.25.0.5/c28e8ff0e64740b3/000ad336?pwd=7sitbn7trtsl2rn1qddr8t15m2' failed: 
_initWebSocket @ BridgeChannel.js:84
Logger.js:154 2022-08-26T12:07:49.044Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-08-26T12:07:49.044Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
Logger.js:154 2022-08-26T12:08:29.684Z [modules/RTC/ScreenObtainer.js] <Object.obtainScreenFromGetDisplayMedia>:  Using getDisplayMedia for screen sharing Object
Logger.js:154 2022-08-26T12:08:45.350Z [JitsiConference.js] <Mh._doReplaceTrack>:  _doReplaceTrack - no P2P JingleSession
Logger.js:154 2022-08-26T12:08:45.363Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=JVB,initiator=false,sid=2cu3e6i10ousr]  Replace track done!
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:08:45.375Z [features/base/tracks] Adding video track - unmuted
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:08:45.452Z [features/noise-suppression] Attempting to set noise suppression enabled state: false
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:08:45.452Z [features/noise-suppression] Noise suppression enabled state already: false
i @ app.bundle.min.js?v=6447:sourcemap:138
Logger.js:154 2022-08-26T12:08:45.453Z [JitsiConference.js] <Mh._doReplaceTrack>:  _doReplaceTrack - no P2P JingleSession
Logger.js:154 2022-08-26T12:08:45.463Z [modules/xmpp/JingleSessionPC.js] <peerconnection.onnegotiationneeded>:  JingleSessionPC[session=JVB,initiator=false,sid=2cu3e6i10ousr] onnegotiationneeded fired on TPC[id=2,type=JVB]
Logger.js:154 2022-08-26T12:08:45.761Z [modules/xmpp/JingleSessionPC.js] <jo.notifyMySSRCUpdate>:  JingleSessionPC[session=JVB,initiator=false,sid=2cu3e6i10ousr] Sending source-add for video ssrcs=30920443,396563615,2460910827
Logger.js:154 2022-08-26T12:08:45.762Z [modules/xmpp/JingleSessionPC.js] <Object.callback>:  JingleSessionPC[session=JVB,initiator=false,sid=2cu3e6i10ousr]  Replace track done!
Logger.js:154 2022-08-26T12:08:45.802Z [modules/RTC/TraceablePeerConnection.js] <Ld.setSenderVideoConstraints>:  TPC[id=2,type=JVB] Setting degradation preference [preference=maintain-resolution,track=LocalTrack[4,video]
Logger.js:154 2022-08-26T12:08:45.803Z [modules/RTC/TraceablePeerConnection.js] <Ld.setSenderVideoConstraints>:  TPC[id=2,type=JVB] setting max height=undefined,encodings=[{"active":false,"adaptivePtime":false,"networkPriority":"low","priority":"low"}]
Logger.js:154 2022-08-26T12:08:46.000Z [modules/RTC/RTCUtils.js] <Wn.<anonymous>>:  Got media constraints:  {"video":false,"audio":{"autoGainControl":true,"deviceId":"web-contents-media-stream://2086:1","echoCancellation":true,"noiseSuppression":true}}
Logger.js:154 2022-08-26T12:08:46.124Z [modules/RTC/RTCUtils.js] onUserMediaSuccess
TrackVADEmitter.js:112 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
_initializeAudioContext @ TrackVADEmitter.js:112
BridgeChannel.js:84 WebSocket connection to 'wss://jitsi.<domain>.com/colibri-ws/172.25.0.5/c28e8ff0e64740b3/000ad336?pwd=7sitbn7trtsl2rn1qddr8t15m2' failed: 
_initWebSocket @ BridgeChannel.js:84
Logger.js:154 2022-08-26T12:08:49.028Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-08-26T12:08:49.028Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
BridgeChannel.js:84 WebSocket connection to 'wss://jitsi.<domain>.com/colibri-ws/172.25.0.5/c28e8ff0e64740b3/000ad336?pwd=7sitbn7trtsl2rn1qddr8t15m2' failed: 
_initWebSocket @ BridgeChannel.js:84
Logger.js:154 2022-08-26T12:09:50.031Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed by server
Logger.js:154 2022-08-26T12:09:50.032Z [modules/RTC/BridgeChannel.js] <e.onclose>:  Channel closed: 1006 
r @ Logger.js:154
Logger.js:154 2022-08-26T12:10:14.095Z [modules/xmpp/ChatRoom.js] <Sr.onPresence>:  entered a4l-24-aug-2022@muc.meet.jitsi/1ed00784 Object
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:10:14.156Z [features/video-quality] <dn.register.deepEquals [as listener]>:  Video quality level for thumbnail height: 426.5, is: 360, override: false, max full res N: 2
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:10:14.247Z [conference.js] <r.<anonymous>>:  USER 1ed00784 connected: kn
app.bundle.min.js?v=6447:sourcemap:138 2022-08-26T12:10:14.492Z [modules/UI/videolayout/LargeVideoManager.js] hover in 1ed00784

**Comment by jallamsetty1** [comment]
Fix for the issue - https://github.com/jitsi/lib-jitsi-meet/pull/2098

**Comment by vskrish11** [comment]
> Fix for the issue - [jitsi/lib-jitsi-meet#2098](https://github.com/jitsi/lib-jitsi-meet/pull/2098)

Thanks, please confirm if that fix was pushed into docker-jitsi-meet also. Our OS is CentOS and so we are using the release from https://github.com/jitsi/docker-jitsi-meet

**Comment by saghul** [comment]
It should be on today's or tomorrow's unstable release.

**Comment by vskrish11** [comment]
Thanks, will wait for the release and test it

**Comment by vskrish11** [comment]
Took about 3 hours ago, the latest unstable builds for all repositories using docker pull and tried a conference. This is the observation -
*Participant 1 (on Chrome), Participant 2 (on Edge)
*Participant 1 shared a tab and Participant 2 was able to view
*The moment Participant 3 joined using Edge browser, Participant 2 stopped seeing Screen share, got just a black box
*When Participant 3 dropped off, Participant 2 could AGAIN see screen share from Participant 1

I have attached browser console logs from Participant 2 as that is there the fluctuation happened. I wonder if we are missing something in configuration but not sure what. Is it possible for you to share what configuration you use for https://meet.jitsi as that works fine ?
[Participant_Two_browser_console_logs.txt](https://github.com/jitsi/docker-jitsi-meet/files/9477492/Participant_Two_browser_console_logs.txt)

**Comment by vskrish11** [comment]
I am attaching the .env file as well, in case that gives you a clue. If the last line is not added, meet keeps disconnecting - "ENABLE_XMPP_WEBSOCKET=0
[env.txt](https://github.com/jitsi/docker-jitsi-meet/files/9477541/env.txt)
"

**Comment by saghul** [comment]
That suggests you have a problem with certificates or proxying.

**Comment by vskrish11** [comment]
Sorry did not get you, which step that I shared above indicates problem with certificates ?

**Comment by saghul** [comment]
The fact that WebSockets didn't work.

It's not a certainty, but it has been the case many times.

How are you handling the ingress traffic? Is it handled directly by the Docker setup?
