### ISSUE TITLE
Etherpad loses focus when speaker changes

### ISSUE THREAD

**Issue by ryanmartinneutrino** [jitsi/docker-jitsi-meet#610]
When the pad is open, it closes as soon as a different person start talking (and the big screen would normally switch to them, but it shouldn't when a pad is open). I think it's this issue:
https://github.com/jitsi/jitsi-meet/issues/5785 
The fix has apparently not been propagated to the docker container. I pulled the container from dockerhub around 18 May 2020 (tag latest).

**Comment by stonerl** [comment]
The bug was fixed but it seems it was introduced again. Having the same issue with `jitsi-meet 2.0.4627-1`

**Comment by echristiaans** [comment]
I can confirm we have this same problem with the latest stable release

**Comment by stonerl** [comment]
Since this is the issue-tracker for docker-specific bugs and the problem is a jitsi-meet core bug @ryanmartinneutrino would you close this one and report in the issue you linked in your first port. I reopened it.

**Comment by ryanmartinneutrino** [comment]
ok - I wasn't sure if this was specific to the version in docker, since the main repo looked like it had fixed it (but then re-introduced apparently?)

**Comment by tusharsonawanes** [comment]
I still face this issue in my 5963 release. Can anybody reconfirm this or is it just me ?
